[package]
name = "shyfyr_client"
version = "0.1.0"
authors = ["Aydar <lesterrry@rambler.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shyfyr = "0.1.0"
clap = "2.33.3"